//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WireGuardServerForWindows.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WireGuardServerForWindows.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Client.
        /// </summary>
        public static string AddClient {
            get {
                return ResourceManager.GetString("AddClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string AddressProperty {
            get {
                return ResourceManager.GetString("AddressProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allowed IPs.
        /// </summary>
        public static string AllowedIpsProperty {
            get {
                return ResourceManager.GetString("AllowedIpsProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Configuration.
        /// </summary>
        public static string ClientConfiguration {
            get {
                return ResourceManager.GetString("ClientConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Configuration(s).
        /// </summary>
        public static string ClientConfigurations {
            get {
                return ResourceManager.GetString("ClientConfigurations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more clients has missing or incorrect configuration..
        /// </summary>
        public static string ClientConfigurationsIncompleteErrorMessage {
            get {
                return ResourceManager.GetString("ClientConfigurationsIncompleteErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No client(s) configured..
        /// </summary>
        public static string ClientConfigurationsMissingErrorMessage {
            get {
                return ResourceManager.GetString("ClientConfigurationsMissingErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure client(s).
        /// </summary>
        public static string ClientConfigurationsResolveText {
            get {
                return ResourceManager.GetString("ClientConfigurationsResolveText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more clients is configured..
        /// </summary>
        public static string ClientConfigurationsSuccessMessage {
            get {
                return ResourceManager.GetString("ClientConfigurationsSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; Client Configuration.
        /// </summary>
        public static string ClientConfigurationTitle {
            get {
                return ResourceManager.GetString("ClientConfigurationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the client?.
        /// </summary>
        public static string ConfirmDeleteClient {
            get {
                return ResourceManager.GetString("ConfirmDeleteClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string DeleteAction {
            get {
                return ResourceManager.GetString("DeleteAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DNS.
        /// </summary>
        public static string DnsProperty {
            get {
                return ResourceManager.GetString("DnsProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client must have a name.
        /// </summary>
        public static string EmptyClientNameError {
            get {
                return ResourceManager.GetString("EmptyClientNameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter public IP:Port as endpoint..
        /// </summary>
        public static string EmptyEndpointValidation {
            get {
                return ResourceManager.GetString("EmptyEndpointValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endpoint port should match Listen Port property..
        /// </summary>
        public static string EndpointPortMismatch {
            get {
                return ResourceManager.GetString("EndpointPortMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endpoint
        ///(Public IP:Port).
        /// </summary>
        public static string EndpointProperty {
            get {
                return ResourceManager.GetString("EndpointProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Configuration File.
        /// </summary>
        public static string ExportConfigurationFileAction {
            get {
                return ResourceManager.GetString("ExportConfigurationFileAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate an IP in the range defined by the server address (currently: {0}).
        /// </summary>
        public static string GenerateClientAddressActionDescription {
            get {
                return ResourceManager.GetString("GenerateClientAddressActionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate from Server.
        /// </summary>
        public static string GenerateFromServerAction {
            get {
                return ResourceManager.GetString("GenerateFromServerAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate QR Code.
        /// </summary>
        public static string GenerateQrCodeAction {
            get {
                return ResourceManager.GetString("GenerateQrCodeAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install tunnel service.
        /// </summary>
        public static string InstallTunnelService {
            get {
                return ResourceManager.GetString("InstallTunnelService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download and install WireGuard.
        /// </summary>
        public static string InstallWireGuard {
            get {
                return ResourceManager.GetString("InstallWireGuard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key must not be empty.
        /// </summary>
        public static string KeyValidationError {
            get {
                return ResourceManager.GetString("KeyValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listen Port.
        /// </summary>
        public static string ListenPortProperty {
            get {
                return ResourceManager.GetString("ListenPortProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string NameProperty {
            get {
                return ResourceManager.GetString("NameProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network must be in valid CIDR notation. For example: 192.168.1.1/24.
        /// </summary>
        public static string NetworkAddressValidationError {
            get {
                return ResourceManager.GetString("NetworkAddressValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port must be between 0 and 65535..
        /// </summary>
        public static string PortRangeValidationError {
            get {
                return ResourceManager.GetString("PortRangeValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port must be numerical..
        /// </summary>
        public static string PortValidationError {
            get {
                return ResourceManager.GetString("PortValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preshared Key.
        /// </summary>
        public static string PresharedKeyProperty {
            get {
                return ResourceManager.GetString("PresharedKeyProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate.
        /// </summary>
        public static string PresharedKeyPropertyAction {
            get {
                return ResourceManager.GetString("PresharedKeyPropertyAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private Key.
        /// </summary>
        public static string PrivateKeyProperty {
            get {
                return ResourceManager.GetString("PrivateKeyProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate.
        /// </summary>
        public static string PrivateKeyPropertyAction {
            get {
                return ResourceManager.GetString("PrivateKeyPropertyAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}:.
        /// </summary>
        public static string PropertyNameFormat {
            get {
                return ResourceManager.GetString("PropertyNameFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public Key.
        /// </summary>
        public static string PublicKeyProperty {
            get {
                return ResourceManager.GetString("PublicKeyProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate.
        /// </summary>
        public static string PublicKeyPropertyAction {
            get {
                return ResourceManager.GetString("PublicKeyPropertyAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Configuration.
        /// </summary>
        public static string ServerConfiguration {
            get {
                return ResourceManager.GetString("ServerConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit server configuration.
        /// </summary>
        public static string ServerConfigurationConfigureText {
            get {
                return ResourceManager.GetString("ServerConfigurationConfigureText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server configuration not completed. Some fields are missing or incorrect..
        /// </summary>
        public static string ServerConfigurationIncompleteErrorMessage {
            get {
                return ResourceManager.GetString("ServerConfigurationIncompleteErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server configuration file (.conf) not found..
        /// </summary>
        public static string ServerConfigurationMissingErrorMessage {
            get {
                return ResourceManager.GetString("ServerConfigurationMissingErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create and edit server configuration.
        /// </summary>
        public static string ServerConfigurationResolveText {
            get {
                return ResourceManager.GetString("ServerConfigurationResolveText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server configuration file (.conf) found..
        /// </summary>
        public static string ServerConfigurationSuccessMessage {
            get {
                return ResourceManager.GetString("ServerConfigurationSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tunnel Service.
        /// </summary>
        public static string TunnelService {
            get {
                return ResourceManager.GetString("TunnelService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tunnel service installed..
        /// </summary>
        public static string TunnelServiceInstalled {
            get {
                return ResourceManager.GetString("TunnelServiceInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tunnel service not installed..
        /// </summary>
        public static string TunnelServiceNotInstalled {
            get {
                return ResourceManager.GetString("TunnelServiceNotInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UNDEFINED.
        /// </summary>
        public static string Undefined {
            get {
                return ResourceManager.GetString("Undefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstall tunnel service.
        /// </summary>
        public static string UninstallTunnelService {
            get {
                return ResourceManager.GetString("UninstallTunnelService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstall WireGuard.
        /// </summary>
        public static string UninstallWireGuard {
            get {
                return ResourceManager.GetString("UninstallWireGuard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}
        ///
        ///{1}.
        /// </summary>
        public static string ValidationErrorFormat {
            get {
                return ResourceManager.GetString("ValidationErrorFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WireGuard.exe.
        /// </summary>
        public static string WireGuardExe {
            get {
                return ResourceManager.GetString("WireGuardExe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found WireGuard.exe in PATH..
        /// </summary>
        public static string WireGuardExeFound {
            get {
                return ResourceManager.GetString("WireGuardExeFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WireGuard.exe is not found in the PATH. It must be downloaded and installed..
        /// </summary>
        public static string WireGuardExeNotFound {
            get {
                return ResourceManager.GetString("WireGuardExeNotFound", resourceCulture);
            }
        }
    }
}
