//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WireGuardServerForWindows.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WireGuardServerForWindows.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string AddressProperty {
            get {
                return ResourceManager.GetString("AddressProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listen Port.
        /// </summary>
        public static string ListenPortProperty {
            get {
                return ResourceManager.GetString("ListenPortProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network must be in valid CIDR notation. For example: 192.168.1.1/24.
        /// </summary>
        public static string NetworkAddressValidationError {
            get {
                return ResourceManager.GetString("NetworkAddressValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port must be between 0 and 65535..
        /// </summary>
        public static string PortRangeValidationError {
            get {
                return ResourceManager.GetString("PortRangeValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port must be numerical..
        /// </summary>
        public static string PortValidationError {
            get {
                return ResourceManager.GetString("PortValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private Key.
        /// </summary>
        public static string PrivateKeyProperty {
            get {
                return ResourceManager.GetString("PrivateKeyProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate.
        /// </summary>
        public static string PrivateKeyPropertyAction {
            get {
                return ResourceManager.GetString("PrivateKeyPropertyAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private key must not be empty.
        /// </summary>
        public static string PrivateKeyValidationError {
            get {
                return ResourceManager.GetString("PrivateKeyValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}:.
        /// </summary>
        public static string PropertyNameFormat {
            get {
                return ResourceManager.GetString("PropertyNameFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}
        ///
        ///{1}.
        /// </summary>
        public static string ValidationErrorFormat {
            get {
                return ResourceManager.GetString("ValidationErrorFormat", resourceCulture);
            }
        }
    }
}
