//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WireGuardServerForWindows.Cli.Options.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WireGuardServerForWindows.Cli.Options.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully added &apos;{0}&apos; to the PATH..
        /// </summary>
        public static string AddedPwdToPath {
            get {
                return ResourceManager.GetString("AddedPwdToPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to load the system&apos;s PATH environment variable..
        /// </summary>
        public static string CantLoadPath {
            get {
                return ResourceManager.GetString("CantLoadPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to detect the current working directory..
        /// </summary>
        public static string CantLoadPwd {
            get {
                return ResourceManager.GetString("CantLoadPwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found that &apos;{0}&apos; was already in the PATH..
        /// </summary>
        public static string FoundPwdInPath {
            get {
                return ResourceManager.GetString("FoundPwdInPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempts to Disable Internet Sharing and then Enable Internet Sharing..
        /// </summary>
        public static string RestartInternetSharingHelpText {
            get {
                return ResourceManager.GetString("RestartInternetSharingHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify the network to share with WireGuard. Useful if internet sharing is not already enabled, or to differentiate when multiple networks are already shared..
        /// </summary>
        public static string RestartInternetSharingNetworkHelpText {
            get {
                return ResourceManager.GetString("RestartInternetSharingNetworkHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adds the directory containing the currently executing ws4w.exe to the system&apos;s PATH environment variable..
        /// </summary>
        public static string SetPathHelpText {
            get {
                return ResourceManager.GetString("SetPathHelpText", resourceCulture);
            }
        }
    }
}
