//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WgServerforWindows.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WgServerforWindows.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Client.
        /// </summary>
        public static string AddClient {
            get {
                return ResourceManager.GetString("AddClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string AddressProperty {
            get {
                return ResourceManager.GetString("AddressProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allowed IPs.
        /// </summary>
        public static string AllowedIpsProperty {
            get {
                return ResourceManager.GetString("AllowedIpsProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allowed IPs.
        /// </summary>
        public static string AllowedRoutableIpsProperty {
            get {
                return ResourceManager.GetString("AllowedRoutableIpsProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot restart internet sharing since multiple networks are currently shared. Specify a network to share with --network..
        /// </summary>
        public static string CannotRestartInternetSharingMultipleNetworks {
            get {
                return ResourceManager.GetString("CannotRestartInternetSharingMultipleNetworks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot restart internet sharing since no network is currently shared. Specify a network to share with --network..
        /// </summary>
        public static string CannotRestartInternetSharingNoNetwork {
            get {
                return ResourceManager.GetString("CannotRestartInternetSharingNoNetwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change client configuration directory.
        /// </summary>
        public static string ChangeClientConfigDirectoryConfigureText {
            get {
                return ResourceManager.GetString("ChangeClientConfigDirectoryConfigureText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current directory is: {0}.
        /// </summary>
        public static string ChangeClientConfigDirectorySuccessMessage {
            get {
                return ResourceManager.GetString("ChangeClientConfigDirectorySuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change server configuration directory.
        /// </summary>
        public static string ChangeServerConfigDirectoryConfigureText {
            get {
                return ResourceManager.GetString("ChangeServerConfigDirectoryConfigureText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current directory is: {0}.
        /// </summary>
        public static string ChangeServerConfigDirectorySuccessMessage {
            get {
                return ResourceManager.GetString("ChangeServerConfigDirectorySuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client address must be at least one IP address, such as 10.232.0.2 or 10.232.0.2/32.
        /// </summary>
        public static string ClientAddressValidationError {
            get {
                return ResourceManager.GetString("ClientAddressValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Configuration.
        /// </summary>
        public static string ClientConfiguration {
            get {
                return ResourceManager.GetString("ClientConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Configuration(s).
        /// </summary>
        public static string ClientConfigurations {
            get {
                return ResourceManager.GetString("ClientConfigurations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more clients has missing or incorrect configuration..
        /// </summary>
        public static string ClientConfigurationsIncompleteErrorMessage {
            get {
                return ResourceManager.GetString("ClientConfigurationsIncompleteErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No client(s) configured..
        /// </summary>
        public static string ClientConfigurationsMissingErrorMessage {
            get {
                return ResourceManager.GetString("ClientConfigurationsMissingErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure client(s).
        /// </summary>
        public static string ClientConfigurationsResolveText {
            get {
                return ResourceManager.GetString("ClientConfigurationsResolveText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more clients is configured..
        /// </summary>
        public static string ClientConfigurationsSuccessMessage {
            get {
                return ResourceManager.GetString("ClientConfigurationsSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; Client Configuration.
        /// </summary>
        public static string ClientConfigurationTitle {
            get {
                return ResourceManager.GetString("ClientConfigurationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count: {0}.
        /// </summary>
        public static string ClientCount {
            get {
                return ResourceManager.GetString("ClientCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Populate from Server.
        /// </summary>
        public static string ClientPresharedKeyPropertyAction {
            get {
                return ResourceManager.GetString("ClientPresharedKeyPropertyAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collapse all.
        /// </summary>
        public static string CollapseAll {
            get {
                return ResourceManager.GetString("CollapseAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the client?.
        /// </summary>
        public static string ConfirmDeleteClient {
            get {
                return ResourceManager.GetString("ConfirmDeleteClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        public static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Details.
        /// </summary>
        public static string CopyDetails {
            get {
                return ResourceManager.GetString("CopyDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string DeleteAction {
            get {
                return ResourceManager.GetString("DeleteAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable.
        /// </summary>
        public static string Disable {
            get {
                return ResourceManager.GetString("Disable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internet sharing is already enabled. Disabling....
        /// </summary>
        public static string DisablingInternetSharing {
            get {
                return ResourceManager.GetString("DisablingInternetSharing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DNS address(es) must be valid IPs, such as 8.8.8.8.
        /// </summary>
        public static string DnsAddressValidationError {
            get {
                return ResourceManager.GetString("DnsAddressValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DNS.
        /// </summary>
        public static string DnsProperty {
            get {
                return ResourceManager.GetString("DnsProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DNS Search Domains.
        /// </summary>
        public static string DnsSearchDomainsProperty {
            get {
                return ResourceManager.GetString("DnsSearchDomainsProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Also known as DNS Suffixes.
        /// </summary>
        public static string DnsSearchDomainsPropertyDescription {
            get {
                return ResourceManager.GetString("DnsSearchDomainsPropertyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DNS Search Domains must be a comma-separated list of names..
        /// </summary>
        public static string DnsSearchDomainsValidationError {
            get {
                return ResourceManager.GetString("DnsSearchDomainsValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client must have a name.
        /// </summary>
        public static string EmptyClientNameError {
            get {
                return ResourceManager.GetString("EmptyClientNameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter public IP:Port or [IPv6]:Port or DomainName:Port as endpoint..
        /// </summary>
        public static string EmptyEndpointValidation {
            get {
                return ResourceManager.GetString("EmptyEndpointValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable.
        /// </summary>
        public static string Enable {
            get {
                return ResourceManager.GetString("Enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabling internet sharing with network &apos;{0}&apos;..
        /// </summary>
        public static string EnablingInternetSharing {
            get {
                return ResourceManager.GetString("EnablingInternetSharing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endpoint port should match Listen Port property..
        /// </summary>
        public static string EndpointPortMismatch {
            get {
                return ResourceManager.GetString("EndpointPortMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endpoint
        ///(Public IP:Port).
        /// </summary>
        public static string EndpointProperty {
            get {
                return ResourceManager.GetString("EndpointProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detect Public IP Address.
        /// </summary>
        public static string EndpointPropertyAction {
            get {
                return ResourceManager.GetString("EndpointPropertyAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempt to detect this machine&apos;s current public (WAN) IP address using ipify.org.
        ///
        ///Note: It is preferable to use a domain name with DDNS to avoid dynamic WAN IPs..
        /// </summary>
        public static string EndpointPropertyActionDescription {
            get {
                return ResourceManager.GetString("EndpointPropertyActionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expand all.
        /// </summary>
        public static string ExpandAll {
            get {
                return ResourceManager.GetString("ExpandAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Configuration File.
        /// </summary>
        public static string ExportConfigurationFileAction {
            get {
                return ResourceManager.GetString("ExportConfigurationFileAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to identify....
        /// </summary>
        public static string FailedToIdentify {
            get {
                return ResourceManager.GetString("FailedToIdentify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count: {0} (filtered from: {1}).
        /// </summary>
        public static string FilteredClientCount {
            get {
                return ResourceManager.GetString("FilteredClientCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate an IP in the range defined by the server address (currently: {0}).
        /// </summary>
        public static string GenerateClientAddressActionDescription {
            get {
                return ResourceManager.GetString("GenerateClientAddressActionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate from Server.
        /// </summary>
        public static string GenerateFromServerAction {
            get {
                return ResourceManager.GetString("GenerateFromServerAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate QR Code.
        /// </summary>
        public static string GenerateQrCodeAction {
            get {
                return ResourceManager.GetString("GenerateQrCodeAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hyper-V may not have installed successfully, so NAT Routing may not be supported on this configuration of Windows. It is recommended to use Internet Connection Sharing instead..
        /// </summary>
        public static string HyperVErrorNatRoutingNotSupported {
            get {
                return ResourceManager.GetString("HyperVErrorNatRoutingNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install tunnel service.
        /// </summary>
        public static string InstallTunnelService {
            get {
                return ResourceManager.GetString("InstallTunnelService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download and install WireGuard.
        /// </summary>
        public static string InstallWireGuard {
            get {
                return ResourceManager.GetString("InstallWireGuard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internet Connection Sharing.
        /// </summary>
        public static string InternetConnectionSharing {
            get {
                return ResourceManager.GetString("InternetConnectionSharing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable Internet Sharing.
        /// </summary>
        public static string InternetSharingConfigure {
            get {
                return ResourceManager.GetString("InternetSharingConfigure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internet Sharing is not enabled, connected peers will have no network access..
        /// </summary>
        public static string InternetSharingError {
            get {
                return ResourceManager.GetString("InternetSharingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Internet Sharing.
        /// </summary>
        public static string InternetSharingResolve {
            get {
                return ResourceManager.GetString("InternetSharingResolve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internet Sharing is enabled..
        /// </summary>
        public static string InternetSharingSuccess {
            get {
                return ResourceManager.GetString("InternetSharingSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internet Sharing.
        /// </summary>
        public static string InternetSharingTitle {
            get {
                return ResourceManager.GetString("InternetSharingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key must not be empty.
        /// </summary>
        public static string KeyValidationError {
            get {
                return ResourceManager.GetString("KeyValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listen Port.
        /// </summary>
        public static string ListenPortProperty {
            get {
                return ResourceManager.GetString("ListenPortProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string NameProperty {
            get {
                return ResourceManager.GetString("NameProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NAT Routing may not be supported on this configuration of Windows. It is recommended to use Internet Connection Sharing instead..
        /// </summary>
        public static string NatRoutingNotSupported {
            get {
                return ResourceManager.GetString("NatRoutingNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network Address Translation.
        /// </summary>
        public static string NetworkAddressTranslation {
            get {
                return ResourceManager.GetString("NetworkAddressTranslation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network must be in valid CIDR notation. For example: 192.168.1.0/24.
        /// </summary>
        public static string NetworkAddressValidationError {
            get {
                return ResourceManager.GetString("NetworkAddressValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable NAT.
        /// </summary>
        public static string NewNatConfigure {
            get {
                return ResourceManager.GetString("NewNatConfigure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NAT Routing.
        /// </summary>
        public static string NewNatName {
            get {
                return ResourceManager.GetString("NewNatName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable NAT.
        /// </summary>
        public static string NewNatResolve {
            get {
                return ResourceManager.GetString("NewNatResolve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NAT is not enabled; connected peers will have no network access..
        /// </summary>
        public static string NewNetError {
            get {
                return ResourceManager.GetString("NewNetError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable Automatic NAT Routing.
        /// </summary>
        public static string NewNetIpAddressTaskSubCommandConfigureText {
            get {
                return ResourceManager.GetString("NewNetIpAddressTaskSubCommandConfigureText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NAT Routing will not be automatically configured on startup. Click to enable..
        /// </summary>
        public static string NewNetIpAddressTaskSubCommandErrorMessage {
            get {
                return ResourceManager.GetString("NewNetIpAddressTaskSubCommandErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Automatic NAT Routing.
        /// </summary>
        public static string NewNetIpAddressTaskSubCommandResolveText {
            get {
                return ResourceManager.GetString("NewNetIpAddressTaskSubCommandResolveText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NAT Routing will be automatically configured on startup. Click to disable..
        /// </summary>
        public static string NewNetIpAddressTaskSubCommandSuccessMessage {
            get {
                return ResourceManager.GetString("NewNetIpAddressTaskSubCommandSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NAT is enabled..
        /// </summary>
        public static string NewNetSuccess {
            get {
                return ResourceManager.GetString("NewNetSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open client configuration directory.
        /// </summary>
        public static string OpenClientConfigDirectoryConfigureText {
            get {
                return ResourceManager.GetString("OpenClientConfigDirectoryConfigureText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open the following path in File Explorer: {0}.
        /// </summary>
        public static string OpenClientConfigDirectorySuccessMessage {
            get {
                return ResourceManager.GetString("OpenClientConfigDirectorySuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open server configuration directory.
        /// </summary>
        public static string OpenServerConfigDirectoryConfigureText {
            get {
                return ResourceManager.GetString("OpenServerConfigDirectoryConfigureText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open the following path in File Explorer: {0}.
        /// </summary>
        public static string OpenServerConfigDirectorySuccessMessage {
            get {
                return ResourceManager.GetString("OpenServerConfigDirectorySuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable.
        /// </summary>
        public static string PersistentInternetSharingDisable {
            get {
                return ResourceManager.GetString("PersistentInternetSharingDisable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Persistent internet sharing is not enabled. The WireGuard tunnel may lose network access after a reboot..
        /// </summary>
        public static string PersistentInternetSharingError {
            get {
                return ResourceManager.GetString("PersistentInternetSharingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable.
        /// </summary>
        public static string PersistentInternetSharingResolve {
            get {
                return ResourceManager.GetString("PersistentInternetSharingResolve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Persistent internet sharing has been enabled, and a Scheduled Task has been created to re-enable sharing upon boot..
        /// </summary>
        public static string PersistentInternetSharingSucecss {
            get {
                return ResourceManager.GetString("PersistentInternetSharingSucecss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Persistent Internet Sharing.
        /// </summary>
        public static string PersistentInternetSharingTitle {
            get {
                return ResourceManager.GetString("PersistentInternetSharingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Persistent Keepalive.
        /// </summary>
        public static string PersistentKeepaliveProperty {
            get {
                return ResourceManager.GetString("PersistentKeepaliveProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Persistent Keepalive must have a numerical value. Use 0 to disable the feature..
        /// </summary>
        public static string PersistentKeepaliveValidationError {
            get {
                return ResourceManager.GetString("PersistentKeepaliveValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Populate the default Allowed IPs from the server configuration (currently: {0}).
        /// </summary>
        public static string PopulateClientAllowedIpsActionDescription {
            get {
                return ResourceManager.GetString("PopulateClientAllowedIpsActionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Populate from Server.
        /// </summary>
        public static string PopulateFromServerAction {
            get {
                return ResourceManager.GetString("PopulateFromServerAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port must be between 0 and 65535..
        /// </summary>
        public static string PortRangeValidationError {
            get {
                return ResourceManager.GetString("PortRangeValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port must be numerical..
        /// </summary>
        public static string PortValidationError {
            get {
                return ResourceManager.GetString("PortValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preshared Key.
        /// </summary>
        public static string PresharedKeyProperty {
            get {
                return ResourceManager.GetString("PresharedKeyProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate.
        /// </summary>
        public static string PresharedKeyPropertyAction {
            get {
                return ResourceManager.GetString("PresharedKeyPropertyAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private Key.
        /// </summary>
        public static string PrivateKeyProperty {
            get {
                return ResourceManager.GetString("PrivateKeyProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate.
        /// </summary>
        public static string PrivateKeyPropertyAction {
            get {
                return ResourceManager.GetString("PrivateKeyPropertyAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revert back to public.
        /// </summary>
        public static string PrivateNetworkConfigure {
            get {
                return ResourceManager.GetString("PrivateNetworkConfigure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network is currently public, meaning that some important protocols and ports will be blocked..
        /// </summary>
        public static string PrivateNetworkError {
            get {
                return ResourceManager.GetString("PrivateNetworkError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make private.
        /// </summary>
        public static string PrivateNetworkResolve {
            get {
                return ResourceManager.GetString("PrivateNetworkResolve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network is private and will allow sharing..
        /// </summary>
        public static string PrivateNetworkSuccess {
            get {
                return ResourceManager.GetString("PrivateNetworkSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable Automatic Private Network.
        /// </summary>
        public static string PrivateNetworkTaskSubCommandConfigureText {
            get {
                return ResourceManager.GetString("PrivateNetworkTaskSubCommandConfigureText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The WireGuard interface will not automatically be set to Private on startup. Click to enable..
        /// </summary>
        public static string PrivateNetworkTaskSubCommandErrorMessage {
            get {
                return ResourceManager.GetString("PrivateNetworkTaskSubCommandErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Automatic Private Network.
        /// </summary>
        public static string PrivateNetworkTaskSubCommandResolveText {
            get {
                return ResourceManager.GetString("PrivateNetworkTaskSubCommandResolveText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The WireGuard interface will automatically be set to Private on startup. Click to disable..
        /// </summary>
        public static string PrivateNetworkTaskSubCommandSuccessMessage {
            get {
                return ResourceManager.GetString("PrivateNetworkTaskSubCommandSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private Network.
        /// </summary>
        public static string PrivateNetworkTitle {
            get {
                return ResourceManager.GetString("PrivateNetworkTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WS4W was unable to enable NAT Routing. Sometimes enabling Hyper-V helps. Would you like to enable Hyper-V now?.
        /// </summary>
        public static string PromptForHyperV {
            get {
                return ResourceManager.GetString("PromptForHyperV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember to reboot after installing Hyper-V. Then try to enable NAT Routing again..
        /// </summary>
        public static string PromptForHyperVReboot {
            get {
                return ResourceManager.GetString("PromptForHyperVReboot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}
        ///    
        ///Current value: {1}.
        /// </summary>
        public static string PropertyFormat {
            get {
                return ResourceManager.GetString("PropertyFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}:.
        /// </summary>
        public static string PropertyNameFormat {
            get {
                return ResourceManager.GetString("PropertyNameFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error generating the public key for the private key: &apos;{0}&apos;..
        /// </summary>
        public static string PublicKeyError {
            get {
                return ResourceManager.GetString("PublicKeyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public Key.
        /// </summary>
        public static string PublicKeyProperty {
            get {
                return ResourceManager.GetString("PublicKeyProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate.
        /// </summary>
        public static string PublicKeyPropertyAction {
            get {
                return ResourceManager.GetString("PublicKeyPropertyAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ScopeAddress registry key does not have the correct value..
        /// </summary>
        public static string ScopeAddressRegistryIncorrect {
            get {
                return ResourceManager.GetString("ScopeAddressRegistryIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose the public network interface whose internet connection should be shared with the WireGuard interface..
        /// </summary>
        public static string SelectInterfaceText {
            get {
                return ResourceManager.GetString("SelectInterfaceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Interface.
        /// </summary>
        public static string SelectInterfaceTitle {
            get {
                return ResourceManager.GetString("SelectInterfaceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify which IPs will be routed from the client to the server. Use 0.0.0.0/0 to route everything. Optionally specify multiple routes, separated by commas, like 10.0.0.0/8, 192.168.1.0/24.
        /// </summary>
        public static string ServerAllowedIpsDescription {
            get {
                return ResourceManager.GetString("ServerAllowedIpsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Configuration.
        /// </summary>
        public static string ServerConfiguration {
            get {
                return ResourceManager.GetString("ServerConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit server configuration.
        /// </summary>
        public static string ServerConfigurationConfigureText {
            get {
                return ResourceManager.GetString("ServerConfigurationConfigureText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server configuration not completed. Some fields are missing or incorrect..
        /// </summary>
        public static string ServerConfigurationIncompleteErrorMessage {
            get {
                return ResourceManager.GetString("ServerConfigurationIncompleteErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server configuration file (.conf) not found..
        /// </summary>
        public static string ServerConfigurationMissingErrorMessage {
            get {
                return ResourceManager.GetString("ServerConfigurationMissingErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create and edit server configuration.
        /// </summary>
        public static string ServerConfigurationResolveText {
            get {
                return ResourceManager.GetString("ServerConfigurationResolveText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server configuration file (.conf) found..
        /// </summary>
        public static string ServerConfigurationSuccessMessage {
            get {
                return ResourceManager.GetString("ServerConfigurationSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Status.
        /// </summary>
        public static string ServerStatus {
            get {
                return ResourceManager.GetString("ServerStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string ServerStatusConfigureText {
            get {
                return ResourceManager.GetString("ServerStatusConfigureText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View a live status of the server (interface) and any configured clients (peers)..
        /// </summary>
        public static string ServerStatusSuccessMessage {
            get {
                return ResourceManager.GetString("ServerStatusSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Server Status.
        /// </summary>
        public static string ServerStatusTitle {
            get {
                return ResourceManager.GetString("ServerStatusTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error syncing the server configuration..
        /// </summary>
        public static string ServerSyncError {
            get {
                return ResourceManager.GetString("ServerSyncError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wg Server for Windows.
        /// </summary>
        public static string SplashScreenText {
            get {
                return ResourceManager.GetString("SplashScreenText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tunnel Service.
        /// </summary>
        public static string TunnelService {
            get {
                return ResourceManager.GetString("TunnelService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tunnel service installed..
        /// </summary>
        public static string TunnelServiceInstalled {
            get {
                return ResourceManager.GetString("TunnelServiceInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tunnel service not installed..
        /// </summary>
        public static string TunnelServiceNotInstalled {
            get {
                return ResourceManager.GetString("TunnelServiceNotInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UNDEFINED.
        /// </summary>
        public static string Undefined {
            get {
                return ResourceManager.GetString("Undefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application has encountered an unexpected error.
        ///
        ///&apos;{0}&apos;.
        /// </summary>
        public static string UnexpectedErrorMessage {
            get {
                return ResourceManager.GetString("UnexpectedErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstall tunnel service.
        /// </summary>
        public static string UninstallTunnelService {
            get {
                return ResourceManager.GetString("UninstallTunnelService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstall WireGuard.
        /// </summary>
        public static string UninstallWireGuard {
            get {
                return ResourceManager.GetString("UninstallWireGuard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully identified!.
        /// </summary>
        public static string Updated {
            get {
                return ResourceManager.GetString("Updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Live.
        /// </summary>
        public static string UpdateLive {
            get {
                return ResourceManager.GetString("UpdateLive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}
        ///    
        ///Current value: {1}
        ///
        ///{2}.
        /// </summary>
        public static string ValidationErrorFormat {
            get {
                return ResourceManager.GetString("ValidationErrorFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WireGuard.exe.
        /// </summary>
        public static string WireGuardExe {
            get {
                return ResourceManager.GetString("WireGuardExe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found WireGuard.exe in PATH..
        /// </summary>
        public static string WireGuardExeFound {
            get {
                return ResourceManager.GetString("WireGuardExeFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WireGuard.exe is not found in the PATH. It must be downloaded and installed..
        /// </summary>
        public static string WireGuardExeNotFound {
            get {
                return ResourceManager.GetString("WireGuardExeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shared network is on a domain, so there is no need to change the profile of the WireGuard network..
        /// </summary>
        public static string WireGuardNetworkOnDomain {
            get {
                return ResourceManager.GetString("WireGuardNetworkOnDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WS4W.
        /// </summary>
        public static string WS4W {
            get {
                return ResourceManager.GetString("WS4W", resourceCulture);
            }
        }
    }
}
