name: 3. Generate Release

on:
  workflow_dispatch:
    inputs:
      version_notes:
        description: 'Version Notes (example, including quotes: " - First change\n - Second Change")'

jobs:
  update_versions:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Determine Version Number
        id: determine_version_number
        run: echo "VERSION_NUMBER=$($env:GITHUB_REF_NAME.Replace('release/v', ''))" >> $env:GITHUB_OUTPUT
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@main
      - name: Download .NET Core Runtime
        run: Invoke-WebRequest https://download.visualstudio.microsoft.com/download/pr/3f56df9d-6dc0-4897-a49b-ea891f9ad0f4/076e353a29908c70e24ba8b8d0daefb8/windowsdesktop-runtime-3.1.21-win-x64.exe -OutFile Installer\windowsdesktop-runtime-3.1.21-win-x64.exe
      - name: Generate Release
        run: Installer\GenerateRelease.ps1
      - name: Publish Release
        uses: softprops/action-gh-release@master
        with:
          files: Installer\WS4WSetup-${{ steps.determine_version_number.outputs.VERSION_NUMBER }}.exe
          tag_name: ${{ steps.determine_version_number.outputs.VERSION_NUMBER }}
          body: ${{ github.event.inputs.version_notes }}
          draft: true
